language: objective-c
osx_image: xcode8.3

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPad Air"              RUN_TESTS="YES"   SEND_TO_COVERALLS="YES"
  before_install:
    - gem install slather

script:
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" test;
    else
      travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" build;
    fi

after_success:
  - if [ $SEND_TO_COVERALLS == "YES" ]; then
      echo "Send to coveralls"
      slather
    fi
notifications:
  email: false